### ISSUE TITLE
Missing auto translation

### ISSUE THREAD

**Issue by vesley** [keshavbhatt/glate#1]
Thank you very much for the nice translation tool. I'm using it on Kubuntu and I didn't faced any issued until now.
What I'm missing is an auto translation when I paste a copied text. Currently, when I paste a text, I have to click with the mouse on the arrow button to initialize the translation. It will be nice if the translation is immediately initialized after the text is pasted.
Also there is no shortcut for the arrow button. F.g. when I enter some text, I have to click manually on the arrow button. Instead using the mouse to click on the button I prefer to use a keyboard shortcut. Or maybe initiate the translation automatically when no keyboards keys are pressed anymore (after 1 second f.g.).

**Comment by keshavbhatt** [comment]
I will add the first feature you talking about, the later one is already there if you hover on the arrow button to bring the tooltip it says shift + enter as shortcut key to trigger the button press event. 
Thanks :)

**Comment by vesley** [comment]
Indeed, I saw the tooltip now :). But it is not working for me. Shift + Enter just puts a new line in the text field.

**Comment by keshavbhatt** [comment]
oh, yeah thats a bug there. it only works when the focus is away from textedit. Will fix that in next release. thanks for letting me know.

**Comment by keshavbhatt** [comment]
Commit 91c7177 fixed this :)
