### ISSUE TITLE
The translation text breaks after "#" symbol

### ISSUE THREAD

**Issue by kazalex** [keshavbhatt/glate#12]
![glate](https://user-images.githubusercontent.com/11914374/187876439-f014301e-7940-45d1-844a-1da86d329cfc.png)

**Comment by keshavbhatt** [comment]
Thanks for reporting, will fix it in next release.

**Comment by keshavbhatt** [comment]
[4718299](https://github.com/keshavbhatt/glate/commit/471829914e58983c287751e738058c19bc98b867) closes this.
Please update Glate to version 3.0
