### ISSUE TITLE
TTS to audio file

### ISSUE THREAD

**Issue by hydrastarmaster** [keshavbhatt/glate#2]
Hi,
TTS voices are nice. It would be useful to have the possibility to save the audio file.
... 
I saw now that the function yet exists in "Share", but the Save button is not always selectable... it may need a check.
Thank you.

**Comment by keshavbhatt** [comment]
can you please provide ways to reproduce this issue ? which save button you talking about ?

**Comment by hydrastarmaster** [comment]
Go for this to debug:
0) after you have a translated text...
1) Push "share/export" button
2) Push "save as audio" button
3) instead of give filename to save, press Esc
4) "Save as audio" button is no more selectable, even exiting and re-entering the window.

**Comment by keshavbhatt** [comment]
will fix this in next version.
