### ISSUE TITLE
When we can expect to see a deb and rpm files

### ISSUE THREAD

**Issue by s1-ranjan** [keshavbhatt/glate#3]
It'll be nice if we can see deb and rpm files of this product, as this will help people who don't prefer to use snap store as the source of packages :)

**Comment by keshavbhatt** [comment]
You can help me in maintaining them if you want :) 
I don't have much knowledge of packaging apps in those formats out of the box, learning will take time and resources.

**Comment by s1-ranjan** [comment]
Okey I can try, but not sure how far..

**Comment by s1-ranjan** [comment]
Does this src folder contains all the source codes?

**Comment by keshavbhatt** [comment]
Yes.

**Comment by s1-ranjan** [comment]
@keshavbhatt  I tried to create a deb file but it did not work for me till now, well by the mean wile I found one more
[useful link](https://github.com/AppImage/pkg2appimage/) I hope this can too help you in any respect to pack the package in appimage format for Linux. 
I was simply expecting the source codes might have been accompanied by config and make files and with the help of the terminals I'll be able to produce a deb file  but... any way I am too learning.

**Comment by keshavbhatt** [comment]
I will try creating .deb

**Comment by keshavbhatt** [comment]
If someone from the user's community will do this and will maintain the packaging I will accept the changes. 
Due to limited human resources, am not planning to maintain deb and rpm myslef right now.
