### ISSUE TITLE
A request for Glate

### ISSUE THREAD

**Issue by Ahmed-E-86** [keshavbhatt/glate#4]
First: Thanks for this amazing application.

In order to use the application I have to keep it opened all the time, but I always press close every time I use it, and I have to open it again, so could you please add tray icon for this application?

That will make it easier to start the application automatically when I start my computer, and it will stay opened in the system tray when I accidentally close it.

I installed your application using snap.

**Comment by keshavbhatt** [comment]
Thanks, I will add these features soon. :)

**Comment by Ahmed-E-86** [comment]
That will be nice. Please let me know when that happens.

**Comment by keshavbhatt** [comment]
i will close this issue and you will get github notification.

**Comment by Ahmed-E-86** [comment]
Understood. Thanks in advance.
