### ISSUE TITLE
Issue with Quick Translate

### ISSUE THREAD

**Issue by Ahmed-E-86** [keshavbhatt/glate#6]
After I choose English as the source language, and press the shortcut for Quick Translate, the source language goes back to Auto Detect, and that is annoying, because I have to set it back to English again to be able to hear the word using TTS engine, otherwise I will get this error message:

![Screenshot_20200811_234055](https://user-images.githubusercontent.com/29783425/89951660-1bb8f780-dc2c-11ea-90c5-c2139828dc85.png)

**Comment by keshavbhatt** [comment]
thanks for reporting, will fix this in next version.

**Comment by keshavbhatt** [comment]
This is intentional, since we dont know what text language you choose to translate.

**Comment by keshavbhatt** [comment]
We do care about the target language you choose to translate into and not the source language.

**Comment by Ahmed-E-86** [comment]
You said that you will fix it. Why did you change your mind?!

There is no option to choose the source language, and I will have to choose it every time I want to use TTS.

**Comment by keshavbhatt** [comment]
May be i don't understand what your trying to say, can you provide instructions to reproduce  the situation ?

**Comment by keshavbhatt** [comment]
yes this is true that the software cannot automatically detect the language of your text, and the TTS engine need source language or i have to make extra queries to first find out the language and then run TTS.

**Comment by Ahmed-E-86** [comment]
Can you just set the language to whatever the user chooses and tell TTS engine to set it to that language?

**Comment by keshavbhatt** [comment]
this is the exact implementation right now.

**Comment by keshavbhatt** [comment]
TTS engine just don't work with auto detect option, as it don't know how to find out what language you using.
