### ISSUE TITLE
How to install Glate from source?

### ISSUE THREAD

**Issue by apandada1** [keshavbhatt/glate#9]
I want to compile glate from source (without snap). I could not find any makefile for it.

How to compile glate from source? And what are the dependencies?

Once I learn how to compile it, I would try to make native packages for Ubuntu and Arch.

**Comment by keshavbhatt** [comment]
You basically need Qt5.5 or higher to  build glate. Open the project pro file in qt creator once your Qt toolkit is set, click Run to build and run the app.

**Comment by keshavbhatt** [comment]
If you have further questions related to this reopen this issue.
